name: 'Read Version'
description: 'Read version from pubspec.yaml'

outputs:
  version:
    description: 'Version name extracted from pubspec.yaml'
    value: ${{ steps.read.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Read version from pubspec.yaml
      id: read
      shell: bash
      run: |
        VERSION_LINE=$(grep '^version:' pubspec.yaml | head -n 1 || echo '')
        VERSION_NAME=${VERSION_LINE#version: }
        VERSION_NAME=${VERSION_NAME%%+*}
        echo "version=$VERSION_NAME" >> "$GITHUB_OUTPUT"
        echo "VERSION_NAME=$VERSION_NAME" >> "$GITHUB_ENV"
